#apiVersion: v1
#kind: Namespace
#metadata:
#  name: nginx-ingress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boan-test
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boan-test-pod
  template:
    metadata:
      labels:
        app: boan-test-pod
    spec:
      containers:
      - name: boan-http
        image: markruler/nodejs-hello-world
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
      - name: proxy-http
        image: nginx:1.18.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5555
---
apiVersion: v1
kind: Service
metadata:
  name: boan-service
  namespace: nginx-ingress
spec:
  type: NodePort
  selector:
    app: boan-test-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30090
    # nodePort: 10090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-1
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-pod
  template:
    metadata:
      labels:
        app: nginx-test-pod
    spec:
      containers:
      - name: simple-http
        image: markruler/nodejs-hello-world
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5001"
        ports:
        - name: http
          containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-1
  namespace: nginx-ingress
spec:
  selector:
    app: nginx-test-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-2
  namespace: nginx-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test-pod-2
  template:
    metadata:
      labels:
        app: nginx-test-pod-2
    spec:
      containers:
      - name: simple-http
        image: markruler/nodejs-hello-world
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5002"
        ports:
        - name: http
          containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: server-service-2
  namespace: nginx-ingress
spec:
  selector:
    app: nginx-test-pod-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5002
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/default-backend: nginx-ingress/server-service
  name: test-ingress
  namespace: nginx-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /test1
        backend:
          serviceName: server-service-1
          servicePort: 80
      - path: /test2
        backend:
          serviceName: server-service-2
          servicePort: 80
  # - host: localhost
  #   http:
  #     paths:
  #     - path: /test3
  #       backend:
  #         serviceName: hello-3
  #         servicePort: 5000
  #     - path: /test4
  #       backend:
  #         serviceName: hello-4
  #         servicePort: 5000
---